### PR TITLE
Add multiple component support

### LINKED ISSUE #63: Support multiple components in changelog renderer template
#55 renderer implementation does not support multiple `component`, and the value is hardcoded to `{agent}`.

The renderer should rely on the `component` field of the fragment instead (by grouping entries kind and then by component).

Reference template: https://github.com/elastic/observability-docs/blob/5e2f16b351769a2d9ed7373d5e3290c16498eefa/docs/en/ingest-management/release-notes/release-notes-8.2.asciidoc

### PR DESCRIPTION
**Pull request by lucianpy**
Closes #63

### CODE REVIEW

**Comment by endorama** [comment]
Overall the proposed solution is ok. Please fix tests and make sure this work in the case of a single component or zero components.

**Comment by lucianpy** [comment]
Currently, components that are either not found in the config or left empty in the fragments are considered unidentified. 

This is reflected both in the title and as an `unidentified component` field in the changelog.

With additonal logic, `unidentified` can be split into `unmatched` and `unspecified` for components not found in the config or left empty in the fragments.

What do you think @endorama?

**Comment by endorama** [comment]
I think this should be addressed with a fatal error: if a component is not matched or identified the tool should produce an error and stop processing the consolidated changelog.

We can notify users of unmatched and unspecified components in the changelog linter, at this stage we want to output correct release notes that can be reused.

**Comment by endorama** [comment]
Discussing how the errors should be handled we noticed there are multiple cases for components configuration based on config and fragment value. Here is the authoritative description of how the tool will manage them (will be updated during the life of this PR).

|`components` configuration value|Fragment `component` field value|Release notes generated|Effect|
|---|---|---|---|
|`[]`|`empty`|✔|Not using components here, release notes should not use components.|
|`["single"]`|`empty`|✔|We assume all fragments are using the configured components. Other components values in the fragment file are rejected.|
|`["first", "second"]`|`empty`|❌|Component unknown and cannot be assumed, emit error and stop processing.|
|`["first", "second"]`|`"foobar"`|❌|Component known and with incorrect value, emit error and stop processing.|
|`["first", "second"]`|`"first"`|✔|Component known and with correct value.|

**Review by endorama — APPROVED** [review]

**Pull request merged**
